"""Add qualification score to opportunities

Revision ID: e5a135a253bb
Revises: 894731014f84
Create Date: 2026-07-04 11:25:28.992858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5a135a253bb'
down_revision: Union[str, Sequence[str], None] = '894731014f84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('qualification_score', sa.Integer(), nullable=True))
    op.add_column('opportunities', sa.Column('qualification_rationale', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunities', 'qualification_rationale')
    op.drop_column('opportunities', 'qualification_score')
    # ### end Alembic commands ###
